name: sentry_flutter_example
description: Demonstrates how to use the sentry_flutter plugin.
version: 0.0.4+4

publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  sentry_flutter: any
  universal_platform: ^1.0.0-nullsafety
  feedback: ^2.0.0
  provider: ^5.0.0

dev_dependencies:
  sentry_dart_plugin: ^1.0.0-alpha.1

dependency_overrides:
  sentry:
    path: ../../dart
  sentry_flutter:
    path: ../
  sentry_dart_plugin:
    path: ../../sentry_dart_plugin

flutter:
  uses-material-design: true

sentry_plugin:
  # enabled by default
  upload_native_symbols: false
  # disabled by default
  include_native_sources: true
  # disabled by default
  upload_source_maps: true
  project: sentry-flutter
  org: sentry-sdks

  # set by env. var. SENTRY_AUTH_TOKEN
  #auth_token:

  # default 'warning'
  log_level: error

  version: sentry_flutter_example@0.0.4+4
